#!/bin/sh

echo '✅ Checking lint and tests...'
npm run pre-commit-check || {
  echo '❌ Lint or tests failed. Please fix them before committing.'
  exit 1
}

echo '✅ All good! Proceeding with commit.'
